defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "docs"
    values:
      layout: docs
      tab: docs
  -
    scope:
      path: "wiki"
    values:
      layout: wiki
      tab: wiki
  -
    scope:
      path: "wiki/basic_know_how"
    values:
      layout: wiki-basic
  -
    scope:
      path: "wiki/general_instructions"
    values:
      layout: wiki-general

sass:
  sass_dir: _sass
  style: :compressed

baseurl: "/restreamer"
highlighter: pygments
lsi: false
markdown: redcarpet
redcarpet:
  extensions: [with_toc_data, tables]
safe: true
source: .
